name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "14.x"

      - name: Create dot env file
        shell: bash
        run: echo "REACT_APP_AZURE_SPEECH_SUBSCRIPTION_KEY=${{ secrets.REACT_APP_AZURE_SPEECH_SUBSCRIPTION_KEY }}%0AREACT_APP_AZURE_SPEECH_SERVICE_REGION=${{ secrets.REACT_APP_AZURE_SPEECH_SERVICE_REGION }}%0AREACT_APP_AZURE_ACCOUNT_NAME=${{ secrets.REACT_APP_AZURE_ACCOUNT_NAME }}%0AREACT_APP_AZURE_SHARED_ACCESS_SIGNATURE=${{ secrets.REACT_APP_AZURE_SHARED_ACCESS_SIGNATURE }}%0AREACT_APP_AZURE_CONTAINER_NAME=${{ secrets.REACT_APP_AZURE_CONTAINER_NAME }}" > .env.local

      - name: Install
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: false

      - name: Create 404.html
        run: cp ./build/index.html ./build/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
